#!/bin/sh

############################

cd ../../build
echo "$PWD"
cmake -D HIPS_BUILD_TESTS=ON -D REACTIONS_ENABLED=ON..
make -j
make install
cd ../run

############################

echo ""
echo "******** Running test.x"
echo ""
./test.x
if [ $? -ne 0 ]; then
  echo "TEST FAILED, ABORT"
  exit 1
fi

############################

echo ""
echo "******** Running test_rxn.x"
echo ""
./test_rxn.x
if [ $? -ne 0 ]; then
  echo "TEST FAILED, ABORT"
  exit 1
fi


